language: node_js

# if: tag IS present

node_js:
  - node

install:
  - npm install

#deploy:
#  provider: npm
#  edge: true
#  email: $NPM_EMAIL
#  api_key: $NPM_TOKEN
#  on:
#    tags: true
#    repo: AngusYang9/html-inline-loader
#  skip_cleanup: true

after_deploy:
  - echo npm published!😊

after_success:
  - npm run coverage
